### ISSUE TITLE
How can I use the bot in the group?

### ISSUE THREAD

**Issue by manizexor-gh** [Kourva/AwesomeChatGPTBot#51]
Hello, thank you to the creator of this source for providing the most unique source, I don't know how I can use the bot in the group, for example, ask a question in the group and the bot will answer it.  Please help.

**Comment by Kourva** [comment]
Hi @manizexor-gh 

You can now use the /chat command along with your prompt to retrieve messages.
for example:
```
/chat Hello
```

The issue was that the chat command handler only worked in private mode, but I have changed it to public mode (groups and supergroups). You can simply re-clone the repository and utilize it.

However, if you prefer to ask in a regular manner (not using the /chat command), you could edit the source code and remove the private check condition from the message handler.


from:
```python
# Message handler for text content in private type chat (for text conversation)
@GPTbot.message_handler(func=lambda x: x.chat.type == "private", content_types=["text"])
def handle_private_messages(message: ClassVar[Any]) -> None:
```
to:
```python
# Message handler for text content in all chat types (for text conversation)
@GPTbot.message_handler(content_types=["text"])
def handle_messages(message: ClassVar[Any]) -> None:
```

Which i changed it also. so you can also ask question normally.

**Comment by manizexor-gh** [comment]
Thanks ❤️

**Comment by manizexor-gh** [comment]
I think I ran into a problem, I want the bot to reply when I type /chat.... not to reply to all messages.

![SmartSelect_20240120_150021_Telegraph](https://github.com/Kourva/AwesomeChatGPTBot/assets/71443383/80259d93-4075-4e70-b15a-ceff43f4fdd3)
